--------------------------------------------------------
-- Archivo creado  - domingo-febrero-09-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LOGIN
--------------------------------------------------------

  CREATE TABLE "JMARULANDA"."LOGIN" 
   (	"ID_LOGIN" NUMBER(*,0), 
	"USUARIO" VARCHAR2(100 BYTE), 
	"CONTRASENA" VARCHAR2(250 BYTE), 
	"ID_TIPO_USUARIO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into JMARULANDA.LOGIN
SET DEFINE OFF;
Insert into JMARULANDA.LOGIN (ID_LOGIN,USUARIO,CONTRASENA,ID_TIPO_USUARIO) values ('1','jmarulanda','sup3r4dm1n','1');
--------------------------------------------------------
--  DDL for Index PK_ID_LOGIN
--------------------------------------------------------

  CREATE UNIQUE INDEX "JMARULANDA"."PK_ID_LOGIN" ON "JMARULANDA"."LOGIN" ("ID_LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_LOGIN
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "JMARULANDA"."TRIGGER_LOGIN" BEFORE
INSERT ON LOGIN FOR EACH ROW
DECLARE
BEGIN
:NEW.ID_LOGIN := SEQ_LOGIN.NEXTVAL;
END;
/
ALTER TRIGGER "JMARULANDA"."TRIGGER_LOGIN" ENABLE;
--------------------------------------------------------
--  Constraints for Table LOGIN
--------------------------------------------------------

  ALTER TABLE "JMARULANDA"."LOGIN" ADD CONSTRAINT "PK_ID_LOGIN" PRIMARY KEY ("ID_LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JMARULANDA"."LOGIN" MODIFY ("ID_TIPO_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "JMARULANDA"."LOGIN" MODIFY ("CONTRASENA" NOT NULL ENABLE);
  ALTER TABLE "JMARULANDA"."LOGIN" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "JMARULANDA"."LOGIN" MODIFY ("ID_LOGIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table LOGIN
--------------------------------------------------------

  ALTER TABLE "JMARULANDA"."LOGIN" ADD CONSTRAINT "FK_ID_TIPO_USUARIO_LOGIN" FOREIGN KEY ("ID_TIPO_USUARIO")
	  REFERENCES "JMARULANDA"."TIPO_USUARIO" ("ID_TIPO_USUARIO") ENABLE;
